### PR TITLE
Develop PNS

### LINKED ISSUE #36: PNS
https://www.chessprogramming.org/Proof-Number_Search

https://minimax.dev/docs/ultimate/pn-search/

> Unlike the search algorithms in the [minimax](https://en.wikipedia.org/wiki/Minimax#Minimax_algorithm_with_alternate_moves) family, PN search is aimed exclusively at exhaustively searching a game node to solve it, which is to say to prove that the position is a forced win for one side (or a forced draw with optimal play by both players). It can be thought of a [best-first](https://en.wikipedia.org/wiki/Best-first_search) search algorithm over the game tree, examining nodes based on an estimate of their promise towards contribuing to a solution to the overall node.

Other than init pn = dn = 1, we can init pn = dn = num. of moves

### PR DESCRIPTION
**Pull request by pwyq**
close #36

### CODE REVIEW

**Comment by pwyq** [comment]
@Samarium150 I think current bug comes from the incorrect Node copying / passing

**Comment by pwyq** [comment]
Thanks to this [repo](https://github.com/kosskas/Project-PNSearch/blob/master/PNSearch.cpp)

**Review by Samarium150 — APPROVED** [review]
Alright, I know it's a memory issue. Although using `new` is definitely less memory-efficient than `vector`, at least it works fine now.

**Review by Samarium150 — APPROVED** [review]

**Comment by pwyq** [comment]
> Alright, I know it's a memory issue. Although using `new` is definitely less memory-efficient than `vector`, at least it works fine now.

we can see how to improve this if we have time later

**Pull request merged**
