### PR TITLE
feat: implement cross-platform constraints

### PR DESCRIPTION
**Pull request by Samarium150**

### CODE REVIEW

**Comment by pwyq** [comment]
still draft?

**Comment by pwyq** [comment]
need to make a windows CI on github actions

**Comment by Samarium150** [comment]
> still draft?

Yeah, having some trouble compiling the cli version.

**Comment by Samarium150** [comment]
> need to make a windows CI on github actions

- [ ] Windows CI

**Comment by Samarium150** [comment]
Whoops. Rename branches will delete the pr

**Pull request closed without merging**
